### ISSUE TITLE
这里可以优化？

### ISSUE THREAD

**Issue by NMSAzulX** [tupac-amaru/YACEP#3]
[1](https://github.com/tupac-amaru/yacep/blob/master/src/TupacAmaru.Yacep/Core/Compiler.Generic.cs#L56)

[2](https://github.com/tupac-amaru/yacep/blob/master/src/TupacAmaru.Yacep/Core/Compiler.Generic.cs#L75)

**Comment by dsc6636926** [comment]
@NMSAzulX 提交一个pr呗～谢谢

**Comment by wushilong** [comment]
@NMSAzulX   非常感谢您关注到的这两块问题!
第一块是这里：
```csharp
            ctorIl.Emit(OpCodes.Ldarg_0);
            ctorIl.Emit(OpCodes.Call, typeof(object).GetConstructor(Type.EmptyTypes));
```
这块的代码确实可以删掉，因为没必要在生成的代码里去调用object构造函数。

第二块是这里：
```csharp
           proxyMethodIl.Emit(OpCodes.Ldc_I4_S , i);
```
这里的问题是在i的值很小的时候，使用Ldc_I4_S不如改成Ldc_I4_x。

非常赞的提议。👍👍👍
求PR。

**Comment by NMSAzulX** [comment]
@dsc6636926 @wushilong  使用emit我觉得对维护和扩展都不是很友好，可以调研一下我的新项目  https://github.com/dotnetcore/Natasha ， 有[日志跟踪](https://github.com/dotnetcore/Natasha/wiki/%E5%BC%95%E6%93%8E%E6%97%A5%E5%BF%97(NScriptLog))、语法检测，构建动态功能十分方便。  目前支持standard2.0版。
